services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: alten_root_password
      MYSQL_DATABASE: remotesync
      MYSQL_USER: alten
      MYSQL_PASSWORD: alten
    networks:
      custom_network:
        ipv4_address: 172.28.0.2
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: alten_root_password
    networks:
      custom_network:
        ipv4_address: 172.28.0.3
    ports:
      - "8081:80"
    restart: always

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"

volumes:
  mysql_data: