package com.alten.remotesync.kernel.utilty.RolePrivileges;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum DefaultRolePrivileges {

    UPDATE_PROFILE("UPDATE_PROFILE"),

    ASSOCIATE_READ("ASSOCIATE:READ"),
    ASSOCIATE_REQUEST("ASSOCIATE:REQUEST"),

    RC_READ("RC:READ"),
    RC_READ_REQUEST("RC:READ_REQUEST"),
    RC_WRITE_ROTATION("RC:WRITE"),
    RC_UPDATE_ROTATION("RC:UPDATE_ROTATION"),
    RC_UPDATE_REQUEST("RC:UPDATE_REQUEST"),

    ADMIN_READ_LOGS("ADMIN:READ_LOGS"),
    ADMIN_READ_PROJECT("ADMIN:READ_PROJECTS"),
    ADMIN_READ_USER("ADMIN:READ_USER"),
    ADMIN_READ_CLIENT("ADMIN:READ_CLIENT"),
    ADMIN_READ_FACTORY("ADMIN:READ_FACTORY"),
    ADMIN_READ_SUB_FACTORY("ADMIN:READ_SUB_FACTORY"),

    ADMIN_WRITE_PROJECT("ADMIN:WRITE_PROJECTS"),
    ADMIN_WRITE_USER("ADMIN:WRITE_USER"),
    ADMIN_WRITE_CLIENT("ADMIN:WRITE_CLIENT"),
    ADMIN_WRITE_FACTORY("ADMIN:WRITE_FACTORY"),
    ADMIN_WRITE_SUB_FACTORY("ADMIN:WRITE_SUB_FACTORY"),

    ADMIN_UPDATE_PROJECT("ADMIN:UPDATE_PROJECTS"),
    ADMIN_UPDATE_USER("ADMIN:UPDATE_USER"),
    ADMIN_UPDATE_CLIENT("ADMIN:UPDATE_CLIENT"),
    ADMIN_UPDATE_FACTORY("ADMIN:UPDATE_FACTORY"),
    ADMIN_UPDATE_SUB_FACTORY("ADMIN:UPDATE_SUB_FACTORY");

    public final String authority;
}
